# © Spark Universe, 2023
# authors: destruc7i0n
# description: This will delete all pet structures to reset the pet system.
# called by: 

structure delete spark:pet_player_1
structure delete spark:pet_player_2
structure delete spark:pet_player_3
structure delete spark:pet_player_4
structure delete spark:pet_player_5
structure delete spark:pet_player_6
structure delete spark:pet_player_7
structure delete spark:pet_player_8
structure delete spark:pet_player_9
structure delete spark:pet_player_10
structure delete spark:pet_player_11
structure delete spark:pet_player_12
structure delete spark:pet_player_13
structure delete spark:pet_player_14
structure delete spark:pet_player_15
structure delete spark:pet_player_16
structure delete spark:pet_player_17
structure delete spark:pet_player_18
structure delete spark:pet_player_19
structure delete spark:pet_player_20
structure delete spark:pet_player_21
structure delete spark:pet_player_22
structure delete spark:pet_player_23
structure delete spark:pet_player_24
structure delete spark:pet_player_25
structure delete spark:pet_player_26
structure delete spark:pet_player_27
structure delete spark:pet_player_28
structure delete spark:pet_player_29
structure delete spark:pet_player_30
structure delete spark:pet_player_31
structure delete spark:pet_player_32
structure delete spark:pet_player_33
structure delete spark:pet_player_34
structure delete spark:pet_player_35
structure delete spark:pet_player_36
structure delete spark:pet_player_37
structure delete spark:pet_player_38
structure delete spark:pet_player_39
structure delete spark:pet_player_40
structure delete spark:pet_player_41
structure delete spark:pet_player_42
structure delete spark:pet_player_43
structure delete spark:pet_player_44
structure delete spark:pet_player_45
structure delete spark:pet_player_46
structure delete spark:pet_player_47
structure delete spark:pet_player_48
structure delete spark:pet_player_49
structure delete spark:pet_player_50
