#dialogue change @e[type=spark:mace_windu,c=1] spark:jedi_council.mace.goodluck
#dialogue change @e[type=spark:plo_koon,c=1] spark:jedi_council.plo_koon.goodluck
#dialogue change @e[type=spark:anakin_skywalker,c=1] spark:jedi_council.anakin.goodluck
#dialogue change @e[type=spark:obi_wan_kenobi,c=1] spark:jedi_council.obiwan.goodluck
#dialogue change @e[type=spark:shaak_ti,c=1] spark:jedi_council.shaak_ti.goodluck
#dialogue change @e[type=spark:eeth_koth,c=1] spark:jedi_council.stass.goodluck
#dialogue change @e[type=spark:kit_fisto,c=1] spark:jedi_council.kit.goodluck
#dialogue change @e[type=spark:saesee_tiin,c=1] spark:jedi_council.saesee.goodluck
#dialogue change @e[type=spark:oppo_rancisis,c=1] spark:jedi_council.coleman.goodluck
#dialogue change @e[type=spark:agen_kolar,c=1] spark:jedi_council.agen.goodluck
#dialogue change @e[type=spark:ki_adi_mundi,c=1] spark:jedi_council.ki_adi.goodluck
dialogue change @e[type=spark:yoda,c=1] spark:jedi_council.yoda.goodluck