# Generated by Bedrock.NET (William Savage)
scoreboard objectives add ui_clock dummy
scoreboard players set _tick ui_clock 0
scoreboard players set _seconds ui_clock 0
scoreboard players set _minutes ui_clock 0