# Generated by Bedrock.NET (William Savage)
scoreboard objectives add ui_clock dummy
scoreboard players add _tick ui_clock 0
scoreboard players add _seconds ui_clock 0
scoreboard players add _minutes ui_clock 0
execute if score _tick ui_clock matches 20.. run scoreboard players add _seconds ui_clock 1
execute if score _tick ui_clock matches 20.. run scoreboard players set _tick ui_clock 0
execute if score _seconds ui_clock matches 60.. run scoreboard players add _minutes ui_clock 1
execute if score _seconds ui_clock matches 60.. run scoreboard players set _seconds ui_clock 0
scoreboard players add _tick ui_clock 1