#try to give lightsaber
event entity @s update_lightsaber

#give lightsaber of host if host has lightsaber and new player hasn't received a lightsaber yet
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_01_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_01_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_02_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_02_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_03_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_03_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_04_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_04_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_05_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_05_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_06_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_06_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_07_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_07_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_08_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_08_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_09_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_09_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_10_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_10_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_11_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_11_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_12_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_12_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_13_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_13_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_14_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_14_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_15_single}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_15_single 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_01_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_01_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_02_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_02_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_03_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_03_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_04_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_04_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_05_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_05_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_06_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_06_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_07_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_07_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_08_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_08_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_09_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_09_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_10_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_10_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_11_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_11_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_12_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_12_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_13_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_13_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_14_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_14_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}
execute unless entity @s[tag=lightsaber_received] if entity @p[tag=data_origin,hasitem={item=spark:lightsaber_15_double}] run replaceitem entity @s slot.inventory 0 spark:lightsaber_15_double 1 0 {"minecraft:keep_on_death":{},"minecraft:item_lock":{"mode":"lock_in_slot"}}

