scoreboard players add .spawnpoint_tmp1 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp2 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp3 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp4 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp5 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp6 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp7 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp8 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp9 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp10 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp11 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp12 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp13 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp14 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp15 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp16 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp17 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp18 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp19 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp20 droid_survival_timer 1
scoreboard players add .spawnpoint_tmp21 droid_survival_timer 1